"""empty message

Revision ID: 7c24fece1040
Revises: e870160cf463
Create Date: 2019-07-20 15:57:51.637050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c24fece1040'
down_revision = 'e870160cf463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('date', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'date')
    # ### end Alembic commands ###
