"""empty message

Revision ID: e870160cf463
Revises: 
Create Date: 2019-07-16 13:56:15.163629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e870160cf463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PROCESSING', 'BLOCKED', 'GOOD_SITE', name='sitestatus'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('whois_data', sa.Text(), nullable=True),
    sa.Column('score', sa.Text(), nullable=True),
    sa.Column('screen', sa.Text(), nullable=True),
    sa.Column('reg_mail', sa.Text(), nullable=True),
    sa.Column('criterions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('site')
    # ### end Alembic commands ###
